<?php
	DEFINE('_WE_HAVE', 'We have ');
	DEFINE('_AND', ' and ');
	DEFINE('_ONLINE',' online');
	DEFINE('_NONE','No Users Online');
	DEFINE('_REG_USERS','Registered Users');	
	DEFINE('_ABOUT_TITLE','ABOUT US');	
	DEFINE('_ABOUT_TEXT1', 'A provincial broadband initiative by the Provincial Government of Zamboanga del Sur.');
	DEFINE('_ABOUT_TEXT2', 'We strive to undertake and provide services to the marginal communities, particularly distant areas since they are “less fortunate” to enjoy or access the modern services.');
	DEFINE('_ABOUT_TEXT3', 'Internet sa Barangay Project - A provincial broadband initiative by the project-oriented Governor Victor J. Yu and his spirited behalf Congresswoman Deputy Speaker Divina Grace C. Yu, who strives to pursue this project emphasizing the government’s goal of providing free internet access even in remote communities.');
	DEFINE('_ABOUT_GVMSG', '"Serving in the Government is Serving the People. This is our utmost responsibility. I hope within 3 years, we can do more for this province. I want this year to be remembered as the first three years of the golden era of Zamboanga del Sur."- Governor Victor Yu');
	DEFINE('_SERVICES', 'McJim Cyberworks services are specializing in Large Network Infrastructures, LAN-WANs, CCTVs, Data Center Deployment, Webhosting and Development, IT Products Supply and Support, IT Consulting, and Management.');
	DEFINE('_POWERED_BY', 'Powered by');
	DEFINE('_OWNER', 'MCJIM CASTILLON MAATA');
	DEFINE('_BRGY', 'Malim');
	DEFINE('_MUN', 'Tabina');
	DEFINE('_PROV', 'Zamboanga del Sur');
	DEFINE('_MPN', 'Mobile');
	DEFINE('_CPN', 'Globe 09776848642, Smart 09386853209');
	DEFINE('_STATE', 'Philippines');
	DEFINE('_FB', 'Facebook');
	DEFINE('_FBTIT', 'Facebook Page');
	DEFINE('_FBPAGE', 'facebook.com/cybermcjim');
	DEFINE('_FBURL', 'https://www.facebook.com/cybermcjim');
	DEFINE('_POST', 'Postal Address');
	DEFINE('_ZIP', '7034');	
	DEFINE('_EMTIT', 'Email Address');
	DEFINE('_EMAIL', 'jcmcyberworks@gmail.com');
	DEFINE('_WEBCOM', 'MCJIM SERVER WEBSITE');
	DEFINE('_DOTCOM', 'MCJIM SERVER DOT COM WEBSITE');
	DEFINE('_MCDEV', 'MCJIM CYBERWORKS & DEVELOPMENT');
	DEFINE('_DESIGN_BY', 'Designed by');
	DEFINE('_MCW', 'MCJIM Cyberworks');
	DEFINE('_WHSP', 'Web Hosting Service Provider');
	DEFINE('_PASS_REQ', 'Password Recovery Request');
	DEFINE('_PASS_REC', 'Password Recovery');
	DEFINE('_USER_FULLNAME', 'Username or Full Name');
	DEFINE('_EMAIL_CPN', 'Email Address or Cellphone Number');
	DEFINE('_TYPE_MSG', 'Type your message here');
	DEFINE('_USR_ACC_REG', 'User Account Registration');
	DEFINE('_SIGN_UP', 'Sign Up! It’s free and always will be.');
?>